// 国際音声字母 (IPA) 辞書データ（記号 -> 名称・分類・説明）
window.IPA_DATA = {
  // === 肺臓気流子音 ===
  // 鼻音
  "m̥": { name: "無声両唇鼻音", en: "Voiceless bilabial nasal", cat: "肺臓気流・鼻音" },
  "m": { name: "有声両唇鼻音", en: "Voiced bilabial nasal", cat: "肺臓気流・鼻音" },
  "ɱ": { name: "有声唇歯鼻音", en: "Voiced labiodental nasal", cat: "肺臓気流・鼻音" },
  "n̼̊": { name: "無声舌唇鼻音", en: "Voiceless linguolabial nasal", cat: "肺臓気流・鼻音" },
  "n̼": { name: "有声舌唇鼻音", en: "Voiced linguolabial nasal", cat: "肺臓気流・鼻音" },
  "n̥": { name: "無声歯茎鼻音", en: "Voiceless alveolar nasal", cat: "肺臓気流・鼻音" },
  "n": { name: "有声歯茎鼻音", en: "Voiced alveolar nasal", cat: "肺臓気流・鼻音" },
  "ɳ̊": { name: "無声そり舌鼻音", en: "Voiceless retroflex nasal", cat: "肺臓気流・鼻音" },
  "ɳ": { name: "有声そり舌鼻音", en: "Voiced retroflex nasal", cat: "肺臓気流・鼻音" },
  "ɲ̊": { name: "無声硬口蓋鼻音", en: "Voiceless palatal nasal", cat: "肺臓気流・鼻音" },
  "ɲ": { name: "有声硬口蓋鼻音", en: "Voiced palatal nasal", cat: "肺臓気流・鼻音" },
  "ŋ̊": { name: "無声軟口蓋鼻音", en: "Voiceless velar nasal", cat: "肺臓気流・鼻音" },
  "ŋ": { name: "有声軟口蓋鼻音", en: "Voiced velar nasal", cat: "肺臓気流・鼻音" },
  "ɴ̥": { name: "無声口蓋垂鼻音", en: "Voiceless uvular nasal", cat: "肺臓気流・鼻音" },
  "ɴ": { name: "有声口蓋垂鼻音", en: "Voiced uvular nasal", cat: "肺臓気流・鼻音" },

  // 破裂音
  "p": { name: "無声両唇破裂音", en: "Voiceless bilabial plosive", cat: "肺臓気流・破裂音" },
  "b": { name: "有声両唇破裂音", en: "Voiced bilabial plosive", cat: "肺臓気流・破裂音" },
  "p̪": { name: "無声唇歯破裂音", en: "Voiceless labiodental plosive", cat: "肺臓気流・破裂音" },
  "b̪": { name: "有声唇歯破裂音", en: "Voiced labiodental plosive", cat: "肺臓気流・破裂音" },
  "t̼": { name: "無声舌唇破裂音", en: "Voiceless linguolabial plosive", cat: "肺臓気流・破裂音" },
  "d̼": { name: "有声舌唇破裂音", en: "Voiced linguolabial plosive", cat: "肺臓気流・破裂音" },
  "t": { name: "無声歯茎破裂音", en: "Voiceless alveolar plosive", cat: "肺臓気流・破裂音" },
  "d": { name: "有声歯茎破裂音", en: "Voiced alveolar plosive", cat: "肺臓気流・破裂音" },
  "ʈ": { name: "無声そり舌破裂音", en: "Voiceless retroflex plosive", cat: "肺臓気流・破裂音" },
  "ɖ": { name: "有声そり舌破裂音", en: "Voiced retroflex plosive", cat: "肺臓気流・破裂音" },
  "c": { name: "無声硬口蓋破裂音", en: "Voiceless palatal plosive", cat: "肺臓気流・破裂音" },
  "ɟ": { name: "有声硬口蓋破裂音", en: "Voiced palatal plosive", cat: "肺臓気流・破裂音" },
  "k": { name: "無声軟口蓋破裂音", en: "Voiceless velar plosive", cat: "肺臓気流・破裂音" },
  "ɡ": { name: "有声軟口蓋破裂音", en: "Voiced velar plosive", cat: "肺臓気流・破裂音" },
  "q": { name: "無声口蓋垂破裂音", en: "Voiceless uvular plosive", cat: "肺臓気流・破裂音" },
  "ɢ": { name: "有声口蓋垂破裂音", en: "Voiced uvular plosive", cat: "肺臓気流・破裂音" },
  "ʡ": { name: "喉頭蓋破裂音", en: "Epiglottal plosive", cat: "肺臓気流・破裂音" },
  "ʔ": { name: "声門破裂音", en: "Glottal stop", cat: "肺臓気流・破裂音" },

  // 破擦音（歯擦音）
  "t͡s": { name: "無声歯茎破擦音（歯擦）", en: "Voiceless alveolar affricate", cat: "肺臓気流・破擦音" },
  "d͡z": { name: "有声歯茎破擦音（歯擦）", en: "Voiced alveolar affricate", cat: "肺臓気流・破擦音" },
  "t͡ʃ": { name: "無声後部歯茎破擦音", en: "Voiceless postalveolar affricate", cat: "肺臓気流・破擦音" },
  "d͡ʒ": { name: "有声後部歯茎破擦音", en: "Voiced postalveolar affricate", cat: "肺臓気流・破擦音" },
  "ʈ͡ʂ": { name: "無声そり舌破擦音", en: "Voiceless retroflex affricate", cat: "肺臓気流・破擦音" },
  "ɖ͡ʐ": { name: "有声そり舌破擦音", en: "Voiced retroflex affricate", cat: "肺臓気流・破擦音" },
  "t͡ɕ": { name: "無声歯茎硬口蓋破擦音", en: "Voiceless alveolo-palatal affricate", cat: "肺臓気流・破擦音" },
  "d͡ʑ": { name: "有声歯茎硬口蓋破擦音", en: "Voiced alveolo-palatal affricate", cat: "肺臓気流・破擦音" },

  // 破擦音（非歯擦音）
  "p͡ɸ": { name: "無声両唇破擦音", en: "Voiceless bilabial affricate", cat: "肺臓気流・破擦音" },
  "b͡β": { name: "有声両唇破擦音", en: "Voiced bilabial affricate", cat: "肺臓気流・破擦音" },
  "p̪͡f": { name: "無声唇歯破擦音", en: "Voiceless labiodental affricate", cat: "肺臓気流・破擦音" },
  "b̪͡v": { name: "有声唇歯破擦音", en: "Voiced labiodental affricate", cat: "肺臓気流・破擦音" },
  "t͡θ": { name: "無声歯破擦音", en: "Voiceless dental affricate", cat: "肺臓気流・破擦音" },
  "d͡ð": { name: "有声歯破擦音", en: "Voiced dental affricate", cat: "肺臓気流・破擦音" },
  "t͡θ̠": { name: "無声歯茎非歯擦破擦音", en: "Voiceless alveolar non-sibilant affricate", cat: "肺臓気流・破擦音" },
  "d͡ð̠": { name: "有声歯茎非歯擦破擦音", en: "Voiced alveolar non-sibilant affricate", cat: "肺臓気流・破擦音" },
  "t̠͡ɹ̠̊˔": { name: "無声後部歯茎非歯擦破擦音", en: "Voiceless postalveolar non-sibilant affricate", cat: "肺臓気流・破擦音" },
  "d̠͡ɹ̠˔": { name: "有声後部歯茎非歯擦破擦音", en: "Voiced postalveolar non-sibilant affricate", cat: "肺臓気流・破擦音" },
  "c͡ç": { name: "無声硬口蓋破擦音", en: "Voiceless palatal affricate", cat: "肺臓気流・破擦音" },
  "ɟ͡ʝ": { name: "有声硬口蓋破擦音", en: "Voiced palatal affricate", cat: "肺臓気流・破擦音" },
  "k͡x": { name: "無声軟口蓋破擦音", en: "Voiceless velar affricate", cat: "肺臓気流・破擦音" },
  "ɡ͡ɣ": { name: "有声軟口蓋破擦音", en: "Voiced velar affricate", cat: "肺臓気流・破擦音" },
  "q͡χ": { name: "無声口蓋垂破擦音", en: "Voiceless uvular affricate", cat: "肺臓気流・破擦音" },
  "ʡ͡ħ": { name: "無声喉頭蓋破擦音", en: "Voiceless epiglottal affricate", cat: "肺臓気流・破擦音" },
  "ʡ͡ʕ": { name: "有声喉頭蓋破擦音", en: "Voiced epiglottal affricate", cat: "肺臓気流・破擦音" },
  "ʔ͡h": { name: "無声声門破擦音", en: "Voiceless glottal affricate", cat: "肺臓気流・破擦音" },

  // 摩擦音（歯擦音）
  "s": { name: "無声歯茎摩擦音（歯擦）", en: "Voiceless alveolar sibilant", cat: "肺臓気流・摩擦音" },
  "z": { name: "有声歯茎摩擦音（歯擦）", en: "Voiced alveolar sibilant", cat: "肺臓気流・摩擦音" },
  "ʃ": { name: "無声後部歯茎摩擦音", en: "Voiceless postalveolar fricative", cat: "肺臓気流・摩擦音" },
  "ʒ": { name: "有声後部歯茎摩擦音", en: "Voiced postalveolar fricative", cat: "肺臓気流・摩擦音" },
  "ʂ": { name: "無声そり舌摩擦音", en: "Voiceless retroflex fricative", cat: "肺臓気流・摩擦音" },
  "ʐ": { name: "有声そり舌摩擦音", en: "Voiced retroflex fricative", cat: "肺臓気流・摩擦音" },
  "ɕ": { name: "無声歯茎硬口蓋摩擦音", en: "Voiceless alveolo-palatal fricative", cat: "肺臓気流・摩擦音" },
  "ʑ": { name: "有声歯茎硬口蓋摩擦音", en: "Voiced alveolo-palatal fricative", cat: "肺臓気流・摩擦音" },

  // 摩擦音（非歯擦音）
  "ɸ": { name: "無声両唇摩擦音", en: "Voiceless bilabial fricative", cat: "肺臓気流・摩擦音" },
  "β": { name: "有声両唇摩擦音", en: "Voiced bilabial fricative", cat: "肺臓気流・摩擦音" },
  "f": { name: "無声唇歯摩擦音", en: "Voiceless labiodental fricative", cat: "肺臓気流・摩擦音" },
  "v": { name: "有声唇歯摩擦音", en: "Voiced labiodental fricative", cat: "肺臓気流・摩擦音" },
  "θ̼": { name: "無声舌唇摩擦音", en: "Voiceless linguolabial fricative", cat: "肺臓気流・摩擦音" },
  "ð̼": { name: "有声舌唇摩擦音", en: "Voiced linguolabial fricative", cat: "肺臓気流・摩擦音" },
  "θ": { name: "無声歯摩擦音", en: "Voiceless dental non-sibilant fricative", cat: "肺臓気流・摩擦音" },
  "ð": { name: "有声歯摩擦音", en: "Voiced dental non-sibilant fricative", cat: "肺臓気流・摩擦音" },
  "θ̱": { name: "無声歯茎非歯擦摩擦音", en: "Voiceless alveolar non-sibilant fricative", cat: "肺臓気流・摩擦音" },
  "ð̠": { name: "有声歯茎非歯擦摩擦音", en: "Voiced alveolar non-sibilant fricative", cat: "肺臓気流・摩擦音" },
  "ɹ̠̊˔": { name: "無声後部歯茎非歯擦摩擦音", en: "Voiceless postalveolar non-sibilant fricative", cat: "肺臓気流・摩擦音" },
  "ɹ̠˔": { name: "有声後部歯茎非歯擦摩擦音", en: "Voiced postalveolar non-sibilant fricative", cat: "肺臓気流・摩擦音" },
  "ç": { name: "無声硬口蓋摩擦音", en: "Voiceless palatal fricative", cat: "肺臓気流・摩擦音" },
  "ʝ": { name: "有声硬口蓋摩擦音", en: "Voiced palatal fricative", cat: "肺臓気流・摩擦音" },
  "x": { name: "無声軟口蓋摩擦音", en: "Voiceless velar fricative", cat: "肺臓気流・摩擦音" },
  "ɣ": { name: "有声軟口蓋摩擦音", en: "Voiced velar fricative", cat: "肺臓気流・摩擦音" },
  "χ": { name: "無声口蓋垂摩擦音", en: "Voiceless uvular fricative", cat: "肺臓気流・摩擦音" },
  "ʁ": { name: "有声口蓋垂摩擦音", en: "Voiced uvular fricative", cat: "肺臓気流・摩擦音" },
  "ħ": { name: "無声咽頭摩擦音", en: "Voiceless pharyngeal fricative", cat: "肺臓気流・摩擦音" },
  "ʕ": { name: "有声咽頭摩擦音", en: "Voiced pharyngeal fricative", cat: "肺臓気流・摩擦音" },
  "h": { name: "無声声門摩擦音", en: "Voiceless glottal fricative", cat: "肺臓気流・摩擦音" },
  "ɦ": { name: "有声声門摩擦音", en: "Voiced glottal fricative", cat: "肺臓気流・摩擦音" },

  // 接近音
  "ɸ˕": { name: "両唇接近音", en: "Bilabial approximant", cat: "肺臓気流・接近音" },
  "β̞": { name: "有声両唇接近音", en: "Voiced bilabial approximant", cat: "肺臓気流・接近音" },
  "ʋ": { name: "唇歯接近音", en: "Labiodental approximant", cat: "肺臓気流・接近音" },
  "θ̞": { name: "歯接近音", en: "Dental approximant", cat: "肺臓気流・接近音" },
  "ɹ̥": { name: "無声歯茎接近音", en: "Voiceless alveolar approximant", cat: "肺臓気流・接近音" },
  "ɹ": { name: "歯茎接近音", en: "Alveolar approximant", cat: "肺臓気流・接近音" },
  "ɻ̊": { name: "無声そり舌接近音", en: "Voiceless retroflex approximant", cat: "肺臓気流・接近音" },
  "ɻ": { name: "そり舌接近音", en: "Retroflex approximant", cat: "肺臓気流・接近音" },
  "j̊": { name: "無声硬口蓋接近音", en: "Voiceless palatal approximant", cat: "肺臓気流・接近音" },
  "j": { name: "硬口蓋接近音（半母音）", en: "Palatal approximant", cat: "肺臓気流・接近音" },
  "ɰ̊": { name: "無声軟口蓋接近音", en: "Voiceless velar approximant", cat: "肺臓気流・接近音" },
  "ɰ": { name: "軟口蓋接近音", en: "Velar approximant", cat: "肺臓気流・接近音" },

  // はじき音
  "ⱱ̟": { name: "両唇はじき音", en: "Bilabial flap", cat: "肺臓気流・はじき音" },
  "ⱱ": { name: "唇歯はじき音", en: "Labiodental flap", cat: "肺臓気流・はじき音" },
  "ɾ̼": { name: "舌唇はじき音", en: "Linguolabial flap", cat: "肺臓気流・はじき音" },
  "ɾ̥": { name: "無声歯茎はじき音", en: "Voiceless alveolar tap", cat: "肺臓気流・はじき音" },
  "ɾ": { name: "有声歯茎はじき音", en: "Alveolar tap", cat: "肺臓気流・はじき音" },
  "ɽ̊": { name: "無声そり舌はじき音", en: "Voiceless retroflex flap", cat: "肺臓気流・はじき音" },
  "ɽ": { name: "有声そり舌はじき音", en: "Retroflex flap", cat: "肺臓気流・はじき音" },
  "ɢ̆": { name: "口蓋垂はじき音", en: "Uvular flap", cat: "肺臓気流・はじき音" },
  "ʡ̯": { name: "喉頭蓋はじき音", en: "Epiglottal flap", cat: "肺臓気流・はじき音" },

  // ふるえ音
  "ʙ": { name: "両唇ふるえ音", en: "Bilabial trill", cat: "肺臓気流・ふるえ音" },
  "r̼": { name: "舌唇ふるえ音", en: "Linguolabial trill", cat: "肺臓気流・ふるえ音" },
  "r̥": { name: "無声歯茎ふるえ音", en: "Voiceless alveolar trill", cat: "肺臓気流・ふるえ音" },
  "r": { name: "有声歯茎ふるえ音", en: "Alveolar trill", cat: "肺臓気流・ふるえ音" },
  "ɽ͡r̥": { name: "無声そり舌ふるえ音", en: "Voiceless retroflex trill", cat: "肺臓気流・ふるえ音" },
  "ɽ͡r": { name: "有声そり舌ふるえ音", en: "Voiced retroflex trill", cat: "肺臓気流・ふるえ音" },
  "ʀ̥": { name: "無声口蓋垂ふるえ音", en: "Voiceless uvular trill", cat: "肺臓気流・ふるえ音" },
  "ʀ": { name: "有声口蓋垂ふるえ音", en: "Uvular trill", cat: "肺臓気流・ふるえ音" },
  "ʜ": { name: "無声喉頭蓋ふるえ音", en: "Voiceless epiglottal trill", cat: "肺臓気流・ふるえ音" },
  "ʢ": { name: "有声喉頭蓋ふるえ音", en: "Voiced epiglottal trill", cat: "肺臓気流・ふるえ音" },

  // 側面破擦音
  "t͡ɬ": { name: "無声歯茎側面破擦音", en: "Voiceless alveolar lateral affricate", cat: "肺臓気流・側面破擦音" },
  "d͡ɮ": { name: "有声歯茎側面破擦音", en: "Voiced alveolar lateral affricate", cat: "肺臓気流・側面破擦音" },
  "ʈ͡ɭ̊˔": { name: "無声そり舌側面破擦音", en: "Voiceless retroflex lateral affricate", cat: "肺臓気流・側面破擦音" },
  "c͡ʎ̥˔": { name: "無声硬口蓋側面破擦音", en: "Voiceless palatal lateral affricate", cat: "肺臓気流・側面破擦音" },
  "k͡ʟ̝̊": { name: "無声軟口蓋側面破擦音", en: "Voiceless velar lateral affricate", cat: "肺臓気流・側面破擦音" },
  "ɡ͡ʟ̝": { name: "有声軟口蓋側面破擦音", en: "Voiced velar lateral affricate", cat: "肺臓気流・側面破擦音" },

  // 側面摩擦音
  "ɬ": { name: "無声歯茎側面摩擦音", en: "Voiceless alveolar lateral fricative", cat: "肺臓気流・側面摩擦音" },
  "ɮ": { name: "有声歯茎側面摩擦音", en: "Voiced alveolar lateral fricative", cat: "肺臓気流・側面摩擦音" },
  "ɭ̊˔": { name: "無声そり舌側面摩擦音", en: "Voiceless retroflex lateral fricative", cat: "肺臓気流・側面摩擦音" },
  "ʎ̥˔": { name: "無声硬口蓋側面摩擦音", en: "Voiceless palatal lateral fricative", cat: "肺臓気流・側面摩擦音" },
  "ʎ̝": { name: "有声硬口蓋側面摩擦音", en: "Voiced palatal lateral fricative", cat: "肺臓気流・側面摩擦音" },
  "ʟ̝̊": { name: "無声軟口蓋側面摩擦音", en: "Voiceless velar lateral fricative", cat: "肺臓気流・側面摩擦音" },
  "ʟ̝": { name: "有声軟口蓋側面摩擦音", en: "Voiced velar lateral fricative", cat: "肺臓気流・側面摩擦音" },

  // 側面接近音
  "l̼": { name: "舌唇側面接近音", en: "Linguolabial lateral approximant", cat: "肺臓気流・側面接近音" },
  "l̥": { name: "無声歯茎側面接近音", en: "Voiceless alveolar lateral approximant", cat: "肺臓気流・側面接近音" },
  "l": { name: "有声歯茎側面接近音", en: "Alveolar lateral approximant", cat: "肺臓気流・側面接近音" },
  "ɭ̊": { name: "無声そり舌側面接近音", en: "Voiceless retroflex lateral approximant", cat: "肺臓気流・側面接近音" },
  "ɭ": { name: "そり舌側面接近音", en: "Retroflex lateral approximant", cat: "肺臓気流・側面接近音" },
  "ʎ̥": { name: "無声硬口蓋側面接近音", en: "Voiceless palatal lateral approximant", cat: "肺臓気流・側面接近音" },
  "ʎ": { name: "硬口蓋側面接近音", en: "Palatal lateral approximant", cat: "肺臓気流・側面接近音" },
  "ʟ": { name: "軟口蓋側面接近音", en: "Velar lateral approximant", cat: "肺臓気流・側面接近音" },
  "ʟ̠": { name: "口蓋垂側面接近音", en: "Uvular lateral approximant", cat: "肺臓気流・側面接近音" },

  // 側面はじき音
  "ɺ̼": { name: "舌唇側面はじき音", en: "Linguolabial lateral flap", cat: "肺臓気流・側面はじき音" },
  "ɺ": { name: "歯茎側面はじき音", en: "Alveolar lateral flap", cat: "肺臓気流・側面はじき音" },
  "ɭ̆": { name: "そり舌側面はじき音", en: "Retroflex lateral flap", cat: "肺臓気流・側面はじき音" },
  "ʎ̯": { name: "硬口蓋側面はじき音", en: "Palatal lateral flap", cat: "肺臓気流・側面はじき音" },
  "ʟ̆": { name: "軟口蓋側面はじき音", en: "Velar lateral flap", cat: "肺臓気流・側面はじき音" },

  // === 非肺臓気流 ===
  // 吸着音
  "ʘ": { name: "両唇吸着音", en: "Bilabial click", cat: "非肺臓気流・吸着音（両唇）" },
  "ʘ̬": { name: "有声両唇吸着音", en: "Voiced bilabial click", cat: "非肺臓気流・吸着音（両唇）" },
  "ʘ̃": { name: "鼻音化両唇吸着音", en: "Nasalized bilabial click", cat: "非肺臓気流・吸着音（両唇）" },
  "ǀ": { name: "歯吸着音", en: "Dental click", cat: "非肺臓気流・吸着音（歯）" },
  "ǀ̬": { name: "有声歯吸着音", en: "Voiced dental click", cat: "非肺臓気流・吸着音（歯）" },
  "ǀ̃": { name: "鼻音化歯吸着音", en: "Nasalized dental click", cat: "非肺臓気流・吸着音（歯）" },
  "ǃ": { name: "（後部）歯茎吸着音", en: "Alveolar click", cat: "非肺臓気流・吸着音（歯茎）" },
  "ǃ̬": { name: "有声歯茎吸着音", en: "Voiced alveolar click", cat: "非肺臓気流・吸着音（歯茎）" },
  "ǃ̃": { name: "鼻音化歯茎吸着音", en: "Nasalized alveolar click", cat: "非肺臓気流・吸着音（歯茎）" },
  "ǂ": { name: "硬口蓋歯茎吸着音", en: "Palatoalveolar click", cat: "非肺臓気流・吸着音（硬口蓋歯茎）" },
  "ǂ̬": { name: "有声硬口蓋歯茎吸着音", en: "Voiced palatoalveolar click", cat: "非肺臓気流・吸着音（硬口蓋歯茎）" },
  "ǂ̃": { name: "鼻音化硬口蓋歯茎吸着音", en: "Nasalized palatoalveolar click", cat: "非肺臓気流・吸着音（硬口蓋歯茎）" },
  "ǁ": { name: "歯茎側面吸着音", en: "Alveolar lateral click", cat: "非肺臓気流・吸着音（側面）" },
  "ǁ̬": { name: "有声歯茎側面吸着音", en: "Voiced alveolar lateral click", cat: "非肺臓気流・吸着音（側面）" },
  "ǁ̃": { name: "鼻音化歯茎側面吸着音", en: "Nasalized alveolar lateral click", cat: "非肺臓気流・吸着音（側面）" },
  "ǃ˞": { name: "そり舌吸着音", en: "Retroflex click", cat: "非肺臓気流・吸着音（そり舌）" },
  "ǃ̬˞": { name: "有声そり舌吸着音", en: "Voiced retroflex click", cat: "非肺臓気流・吸着音（そり舌）" },
  "ǃ̃˞": { name: "鼻音化そり舌吸着音", en: "Nasalized retroflex click", cat: "非肺臓気流・吸着音（そり舌）" },
  "ʘ̃ˀ": { name: "声門化鼻音化両唇吸着音", en: "Glottalized nasalized bilabial click", cat: "非肺臓気流・吸着音（複合・修飾）" },
  "ʘˀ": { name: "声門化両唇吸着音", en: "Glottalized bilabial click", cat: "非肺臓気流・吸着音（複合・修飾）" },
  "ˀʘ̃": { name: "前声門化両唇吸着音", en: "Pre-glottalized bilabial click", cat: "非肺臓気流・吸着音（複合・修飾）" },
  "ʘ͡q": { name: "口蓋垂両唇吸着音", en: "Uvular bilabial click", cat: "非肺臓気流・吸着音（口蓋垂両唇）" },
  "ʘ͡qχ": { name: "口蓋垂破擦両唇吸着音", en: "Uvular affricated bilabial click", cat: "非肺臓気流・吸着音（口蓋垂破擦）" },
  "ʘ͡qʼ": { name: "放出音化両唇吸着音", en: "Ejective bilabial click", cat: "非肺臓気流・吸着音（放出）" },
  "ʘ͡qχʼ": { name: "放出破擦口蓋垂両唇吸着音", en: "Ejective affricated uvular bilabial click", cat: "非肺臓気流・吸着音（放出破擦）" },
  "¡": { name: "亜歯茎吸着音", en: "Subapical retroflex click", cat: "非肺臓気流・吸着音（亜歯茎）" },
  "ʞ": { name: "軟口蓋吸着音", en: "Velar click", cat: "非肺臓気流・吸着音（軟口蓋）" },

  // 入破音
  "ɓ": { name: "有声両唇入破音", en: "Voiced bilabial implosive", cat: "非肺臓気流・入破音（両唇）" },
  "ɗ": { name: "有声歯茎入破音", en: "Voiced alveolar implosive", cat: "非肺臓気流・入破音（歯茎）" },
  "ᶑ": { name: "有声そり舌入破音", en: "Voiced retroflex implosive", cat: "非肺臓気流・入破音（そり舌）" },
  "ʄ": { name: "有声硬口蓋入破音", en: "Voiced palatal implosive", cat: "非肺臓気流・入破音（硬口蓋）" },
  "ɠ": { name: "有声軟口蓋入破音", en: "Voiced velar implosive", cat: "非肺臓気流・入破音（軟口蓋）" },
  "ʛ": { name: "有声口蓋垂入破音", en: "Voiced uvular implosive", cat: "非肺臓気流・入破音（口蓋垂）" },
  "ɓ̥": { name: "無声両唇入破音", en: "Voiceless bilabial implosive", cat: "非肺臓気流・入破音（両唇）" },
  "ɗ̥": { name: "無声歯茎入破音", en: "Voiceless alveolar implosive", cat: "非肺臓気流・入破音（歯茎）" },
  "ᶑ̥": { name: "無声そり舌入破音", en: "Voiceless retroflex implosive", cat: "非肺臓気流・入破音（そり舌）" },
  "ʄ̊": { name: "無声硬口蓋入破音", en: "Voiceless palatal implosive", cat: "非肺臓気流・入破音（硬口蓋）" },
  "ɠ̊": { name: "無声軟口蓋入破音", en: "Voiceless velar implosive", cat: "非肺臓気流・入破音（軟口蓋）" },
  "ʛ̥": { name: "無声口蓋垂入破音", en: "Voiceless uvular implosive", cat: "非肺臓気流・入破音（口蓋垂）" },

  // 放出音
  "pʼ": { name: "両唇放出音", en: "Bilabial ejective", cat: "非肺臓気流・放出音（両唇）" },
  "tʼ": { name: "歯茎放出音", en: "Alveolar ejective", cat: "非肺臓気流・放出音（歯茎）" },
  "ʈʼ": { name: "そり舌放出音", en: "Retroflex ejective", cat: "非肺臓気流・放出音（そり舌）" },
  "cʼ": { name: "硬口蓋放出音", en: "Palatal ejective", cat: "非肺臓気流・放出音（硬口蓋）" },
  "kʼ": { name: "軟口蓋放出音", en: "Velar ejective", cat: "非肺臓気流・放出音（軟口蓋）" },
  "qʼ": { name: "口蓋垂放出音", en: "Uvular ejective", cat: "非肺臓気流・放出音（口蓋垂）" },
  "ʡʼ": { name: "喉頭蓋放出音", en: "Epiglottal ejective", cat: "非肺臓気流・放出音（喉頭蓋）" },
  "fʼ": { name: "唇歯摩擦放出音", en: "Labiodental ejective fricative", cat: "非肺臓気流・放出音（唇歯）" },
  "θʼ": { name: "歯摩擦放出音", en: "Dental ejective fricative", cat: "非肺臓気流・放出音（歯）" },
  "sʼ": { name: "歯茎摩擦放出音", en: "Alveolar ejective fricative", cat: "非肺臓気流・放出音（歯茎）" },
  "ɬʼ": { name: "側面摩擦放出音", en: "Lateral alveolar ejective fricative", cat: "非肺臓気流・放出音（側面）" },
  "ʃʼ": { name: "後部歯茎摩擦放出音", en: "Postalveolar ejective fricative", cat: "非肺臓気流・放出音（後部歯茎）" },
  "ʂʼ": { name: "そり舌摩擦放出音", en: "Retroflex ejective fricative", cat: "非肺臓気流・放出音（そり舌）" },
  "ɕʼ": { name: "歯茎硬口蓋摩擦放出音", en: "Alveolo-palatal ejective fricative", cat: "非肺臓気流・放出音（歯茎硬口蓋）" },
  "xʼ": { name: "軟口蓋摩擦放出音", en: "Velar ejective fricative", cat: "非肺臓気流・放出音（軟口蓋）" },
  "χʼ": { name: "口蓋垂摩擦放出音", en: "Uvular ejective fricative", cat: "非肺臓気流・放出音（口蓋垂）" },
  "t͡sʼ": { name: "歯茎破擦放出音", en: "Alveolar ejective affricate", cat: "非肺臓気流・放出音（歯茎）" },
  "t͡ɬʼ": { name: "歯茎側面破擦放出音", en: "Alveolar lateral ejective affricate", cat: "非肺臓気流・放出音（側面）" },
  "t͡ʃʼ": { name: "後部歯茎破擦放出音", en: "Postalveolar ejective affricate", cat: "非肺臓気流・放出音（後部歯茎）" },
  "ʈ͡ʂʼ": { name: "そり舌破擦放出音", en: "Retroflex ejective affricate", cat: "非肺臓気流・放出音（そり舌）" },
  "t͡ɕʼ": { name: "歯茎硬口蓋破擦放出音", en: "Alveolo-palatal ejective affricate", cat: "非肺臓気流・放出音（歯茎硬口蓋）" },
  "c͡ʎ̝̥ʼ": { name: "硬口蓋側面破擦放出音", en: "Palatal lateral ejective affricate", cat: "非肺臓気流・放出音（硬口蓋側面）" },
  "k͡xʼ": { name: "軟口蓋破擦放出音", en: "Velar ejective affricate", cat: "非肺臓気流・放出音（軟口蓋）" },
  "k͡ʟ̝̊ʼ": { name: "軟口蓋側面破擦放出音", en: "Velar lateral ejective affricate", cat: "非肺臓気流・放出音（軟口蓋側面）" },
  "q͡χʼ": { name: "口蓋垂破擦放出音", en: "Uvular ejective affricate", cat: "非肺臓気流・放出音（口蓋垂）" },

  // === 二重調音 ===
  "ʍ": { name: "無声両唇軟口蓋接近音", en: "Voiceless labial-velar approximant", cat: "二重調音（両唇軟口蓋）" },
  "w": { name: "有声両唇軟口蓋接近音", en: "Voiced labial-velar approximant", cat: "二重調音（両唇軟口蓋）" },
  "ɥ": { name: "有声両唇硬口蓋接近音", en: "Voiced labial-palatal approximant", cat: "二重調音（両唇硬口蓋）" },
  "ɫ": { name: "軟口蓋化歯茎側面接近音", en: "Velarized alveolar lateral approximant", cat: "二重調音（軟口蓋化歯茎）" },
  "k͡p": { name: "無声両唇軟口蓋破裂音", en: "Voiceless labial-velar plosive", cat: "二重調音（両唇軟口蓋）" },
  "ɡ͡b": { name: "有声両唇軟口蓋破裂音", en: "Voiced labial-velar plosive", cat: "二重調音（両唇軟口蓋）" },
  "ŋ͡m": { name: "両唇軟口蓋鼻音", en: "Labial-velar nasal", cat: "二重調音（両唇軟口蓋）" },
  "ɧ": { name: "無声後部歯茎軟口蓋摩擦音", en: "Sj-sound", cat: "二重調音（後部歯茎軟口蓋）" },
  "t͡p": { name: "無声両唇歯茎破裂音", en: "Voiceless labial-alveolar plosive", cat: "二重調音（両唇歯茎）" },
  "d͡b": { name: "有声両唇歯茎破裂音", en: "Voiced labial-alveolar plosive", cat: "二重調音（両唇歯茎）" },
  "n͡m": { name: "両唇歯茎鼻音", en: "Labial-alveolar nasal", cat: "二重調音（両唇歯茎）" },
  "q͡ʡ": { name: "口蓋垂喉頭蓋破裂音", en: "Uvular-epiglottal plosive", cat: "二重調音（口蓋垂喉頭蓋）" },

  // === 母音 ===
  "i": { name: "非円唇前舌狭母音", en: "Close front unrounded vowel", cat: "母音・狭母音" },
  "y": { name: "円唇前舌狭母音", en: "Close front rounded vowel", cat: "母音・狭母音" },
  "ɨ": { name: "非円唇中舌狭母音", en: "Close central unrounded vowel", cat: "母音・狭母音" },
  "ʉ": { name: "円唇中舌狭母音", en: "Close central rounded vowel", cat: "母音・狭母音" },
  "ɯ": { name: "非円唇後舌狭母音", en: "Close back unrounded vowel", cat: "母音・狭母音" },
  "u": { name: "円唇後舌狭母音", en: "Close back rounded vowel", cat: "母音・狭母音" },
  "ɪ": { name: "非円唇前舌め広めの狭母音", en: "Near-close near-front unrounded vowel", cat: "母音・広めの狭" },
  "ʏ": { name: "円唇前舌め広めの狭母音", en: "Near-close near-front rounded vowel", cat: "母音・広めの狭" },
  "ɪ̈": { name: "中舌広めの狭母音", en: "Near-close central unrounded vowel", cat: "母音・広めの狭" },
  "ʊ̈": { name: "円唇中舌広めの狭母音", en: "Near-close central rounded vowel", cat: "母音・広めの狭" },
  "ʊ": { name: "円唇後舌め広めの狭母音", en: "Near-close near-back rounded vowel", cat: "母音・広めの狭" },
  "e": { name: "非円唇前舌半狭母音", en: "Close-mid front unrounded vowel", cat: "母音・半狭母音" },
  "ø": { name: "円唇前舌半狭母音", en: "Close-mid front rounded vowel", cat: "母音・半狭母音" },
  "ɘ": { name: "非円唇中舌半狭母音", en: "Close-mid central unrounded vowel", cat: "母音・半狭母音" },
  "ɵ": { name: "円唇中舌半狭母音", en: "Close-mid central rounded vowel", cat: "母音・半狭母音" },
  "ɤ": { name: "非円唇後舌半狭母音", en: "Close-mid back unrounded vowel", cat: "母音・半狭母音" },
  "o": { name: "円唇後舌半狭母音", en: "Close-mid back rounded vowel", cat: "母音・半狭母音" },
  "e̞": { name: "非円唇前舌中央母音", en: "Mid front unrounded vowel", cat: "母音・中央母音" },
  "ø̞": { name: "円唇前舌中央母音", en: "Mid front rounded vowel", cat: "母音・中央母音" },
  "ə": { name: "中舌中央母音（シュワー）", en: "Mid central vowel (Schwa)", cat: "母音・中央母音" },
  "ɵ̞": { name: "円唇中舌中央母音", en: "Mid central rounded vowel", cat: "母音・中央母音" },
  "ɤ̞": { name: "非円唇後舌中央母音", en: "Mid back unrounded vowel", cat: "母音・中央母音" },
  "o̞": { name: "円唇後舌中央母音", en: "Mid back rounded vowel", cat: "母音・中央母音" },
  "ɛ": { name: "非円唇前舌半広母音", en: "Open-mid front unrounded vowel", cat: "母音・半広母音" },
  "œ": { name: "円唇前舌半広母音", en: "Open-mid front rounded vowel", cat: "母音・半広母音" },
  "ɜ": { name: "非円唇中舌半広母音", en: "Open-mid central unrounded vowel", cat: "母音・半広母音" },
  "ɞ": { name: "円唇中舌半広母音", en: "Open-mid central rounded vowel", cat: "母音・半広母音" },
  "ʌ": { name: "非円唇後舌半広母音", en: "Open-mid back unrounded vowel", cat: "母音・半広母音" },
  "ɔ": { name: "円唇後舌半広母音", en: "Open-mid back rounded vowel", cat: "母音・半広母音" },
  "æ": { name: "非円唇前舌狭めの広母音", en: "Near-open front unrounded vowel", cat: "母音・狭めの広" },
  "ɐ": { name: "中舌狭めの広母音", en: "Near-open central vowel", cat: "母音・狭めの広" },
  "a": { name: "非円唇前舌広母音", en: "Open front unrounded vowel", cat: "母音・広母音" },
  "ɶ": { name: "円唇前舌広母音", en: "Open front rounded vowel", cat: "母音・広母音" },
  "ä": { name: "非円唇中舌広母音", en: "Open central unrounded vowel", cat: "母音・広母音" },
  "ɒ̈": { name: "円唇中舌広母音", en: "Open central rounded vowel", cat: "母音・広母音" },
  "ɑ": { name: "非円唇後舌広母音", en: "Open back unrounded vowel", cat: "母音・広母音" },
  "ɒ": { name: "円唇後舌広母音", en: "Open back rounded vowel", cat: "母音・広母音" },

  // === 補助記号（ダイアクリティカルマーク） ===
  // 1. 音節性 (Syllabicity)
  "̩": { name: "音節主音（下符）", en: "Syllabic", cat: "補助記号・音節性" },
  "̯": { name: "音節副音（下符）", en: "Non-syllabic", cat: "補助記号・音節性" },

  // 2. 子音解放 (Consonant Release)
  "ʰ": { name: "帯気音（気息）", en: "Aspirated", cat: "補助記号・子音解放" },
  "̚": { name: "内破音（無開放）", en: "No audible release", cat: "補助記号・子音解放" },
  "ⁿ": { name: "鼻腔開放", en: "Nasal release", cat: "補助記号・子音解放" },
  "ˡ": { name: "側面開放", en: "Lateral release", cat: "補助記号・子音解放" },

  // 3. 発声・声門状態 (Phonation)
  "̥": { name: "無声化（下符丸）", en: "Voiceless", cat: "補助記号・発声" },
  "̬": { name: "有声化（下符くさび）", en: "Voiced", cat: "補助記号・発声" },
  "̤": { name: "息漏れ声（下符二重ドット）", en: "Breathy voiced", cat: "補助記号・発声" },
  "̰": { name: "軋み声（下符チルダ）", en: "Creaky voiced", cat: "補助記号・発声" },

  // 4. 調音位置・舌の位置 (Primary Articulation)
  "̪": { name: "歯音化（下符ブリッジ）", en: "Dental", cat: "補助記号・調音" },
  "̼": { name: "舌唇音化（下符カモメ）", en: "Linguolabial", cat: "補助記号・調音" },
  "̺": { name: "舌尖音化（下符反転ブリッジ）", en: "Apical", cat: "補助記号・調音" },
  "̻": { name: "舌端音化（下符四角）", en: "Laminal", cat: "補助記号・調音" },
  "̟": { name: "前寄り（下符プラス）", en: "Advanced", cat: "補助記号・調音" },
  "̠": { name: "後寄り（下符マイナス）", en: "Retracted", cat: "補助記号・調音" },
  "̈": { name: "中舌寄り（上符ダイエレシス）", en: "Centralized", cat: "補助記号・調音" },
  "̽": { name: "中央寄り（上符x）", en: "Mid-centralized", cat: "補助記号・調音" },
  "̝": { name: "上寄り（下符）", en: "Raised", cat: "補助記号・調音" },
  "˔": { name: "上寄り（独立修飾符）", en: "Raised (independent)", cat: "補助記号・調音" },
  "ɹ̝": { name: "摩擦音化接近音", en: "Fricative approximant", cat: "補助記号・調音" },
  "̞": { name: "下寄り（下符）", en: "Lowered", cat: "補助記号・調音" },
  "˕": { name: "下寄り（独立修飾符）", en: "Lowered (independent)", cat: "補助記号・調音" },

  // 5. 同時調音・二次調音 (Co-articulation & Secondary Articulation)
  "̃": { name: "鼻音化（上符チルダ）", en: "Nasalized", cat: "補助記号・同時調音" },
  "ʷ": { name: "唇音化（円唇化）", en: "Labialized", cat: "補助記号・同時調音" },
  "ʲ": { name: "硬口蓋化（口蓋化）", en: "Palatalized", cat: "補助記号・同時調音" },
  "ˠ": { name: "軟口蓋化", en: "Velarized", cat: "補助記号・同時調音" },
  "ˤ": { name: "咽頭化", en: "Pharyngealized", cat: "補助記号・同時調音" },
  "̴": { name: "軟口蓋化または咽頭化（重ねチルダ）", en: "Velarized or Pharyngealized", cat: "補助記号・同時調音" },
  "ᶣ": { name: "両唇硬口蓋化", en: "Labial-palatalized", cat: "補助記号・同時調音" },
  "̹": { name: "強めの円唇（下符）", en: "More rounded", cat: "補助記号・同時調音" },
  "̜": { name: "弱めの円唇（下符）", en: "Less rounded", cat: "補助記号・同時調音" },
  "˞": { name: "R音性（直後付加符）", en: "Rhoticity", cat: "補助記号・同時調音" },
  "ɚ": { name: "R音性シュワー", en: "Rhotacized schwa", cat: "補助記号・同時調音" },
  "ɝ": { name: "R音性中舌半広母音", en: "Rhotacized open-mid central vowel", cat: "補助記号・同時調音" },

  // 6. 気流機構 (Airstream)
  "̘": { name: "舌根前進（+ATR）", en: "Advanced tongue root", cat: "補助記号・気流" },
  "̙": { name: "舌根後退（-ATR）", en: "Retracted tongue root", cat: "補助記号・気流" },

  // === 超分節要素・声調 ===
  "ˈ": { name: "第一強勢（主アクセント）", en: "Primary stress", cat: "超分節要素" },
  "ˌ": { name: "第二強勢（副アクセント）", en: "Secondary stress", cat: "超分節要素" },
  "ː": { name: "長音（長音記号）", en: "Long", cat: "超分節要素" },
  "ˑ": { name: "半長音（半長記号）", en: "Half-long", cat: "超分節要素" },
  "̆": { name: "超短（上符短音符）", en: "Extra-short", cat: "超分節要素" },
  ".": { name: "音節境界（シラブル区切り）", en: "Syllable break", cat: "超分節要素" },
  "͡": { name: "二重調音（上タイバー連結線）", en: "Tie bar (above)", cat: "超分節要素" },
  "‿": { name: "連結（下タイバー／リエゾン）", en: "Linking (absence of a break)", cat: "超分節要素" },
  "|": { name: "小さな切れ目（韻脚境界）", en: "Minor (foot) group", cat: "超分節要素" },
  "‖": { name: "大きな切れ目（イントネーション句）", en: "Major (intonation) group", cat: "超分節要素" },

  // 声調記号（アクセント符）
  "̋": { name: "超高調（二重鋭アクセント）", en: "Extra high tone", cat: "声調・水平レベル調" },
  "́": { name: "高調（鋭アクセント）", en: "High tone", cat: "声調・水平レベル調" },
  "̄": { name: "中調（マクロン）", en: "Mid tone", cat: "声調・水平レベル調" },
  "̀": { name: "低調（重アクセント）", en: "Low tone", cat: "声調・水平レベル調" },
  "̏": { name: "超低調（二重重アクセント）", en: "Extra low tone", cat: "声調・水平レベル調" },

  // 五段階声調バー (Chao Tone Letters) - 合字対応
  "˥": { name: "超高調バー (55)", en: "Extra high tone letter", cat: "声調・五段階声調バー" },
  "˦": { name: "高調バー (44)", en: "High tone letter", cat: "声調・五段階声調バー" },
  "˧": { name: "中調バー (33)", en: "Mid tone letter", cat: "声調・五段階声調バー" },
  "˨": { name: "低調バー (22)", en: "Low tone letter", cat: "声調・五段階声調バー" },
  "˩": { name: "超低調バー (11)", en: "Extra low tone letter", cat: "声調・五段階声調バー" },

  // 変調・曲線声調（合字表記）
  "̌": { name: "上昇調（キャロン）", en: "Rising tone", cat: "声調・変動調" },
  "˩˥": { name: "上昇調合字バー (15)", en: "Rising tone ligature", cat: "声調・変動合字バー" },
  "̂": { name: "下降調（サーカムフレックス）", en: "Falling tone", cat: "声調・変動調" },
  "˥˩": { name: "下降調合字バー (51)", en: "Falling tone ligature", cat: "声調・変動合字バー" },
  "᷄": { name: "高上昇調", en: "High rising tone", cat: "声調・変動調" },
  "˧˥": { name: "高上昇調合字バー (35)", en: "High rising tone ligature", cat: "声調・変動合字バー" },
  "᷇": { name: "低上昇／高下降調", en: "Low rising / High falling", cat: "声調・変動調" },
  "˥˦": { name: "高下降調合字バー (54)", en: "High-falling tone ligature (54)", cat: "声調・変動合字バー" },
  "˥˧": { name: "高下降調合字バー (53)", en: "High falling tone ligature", cat: "声調・変動合字バー" },
  "᷈": { name: "昇降調", en: "Peaking tone (rise-fall)", cat: "声調・変動調" },
  "˦˥˦": { name: "昇降調合字バー (454)", en: "Peaking tone ligature", cat: "声調・変動合字バー" },
  "˨˩˦": { name: "降昇調合字バー (214)", en: "Dipping tone ligature", cat: "声調・変動合字バー" },
  "˩˧": { name: "低上昇調合字バー (13)", en: "Low rising tone ligature", cat: "声調・変動合字バー" },
  "˧˩": { name: "低下降調合字バー (31)", en: "Low falling tone ligature", cat: "声調・変動合字バー" },

  // イントネーション
  "ꜜ": { name: "ダウンステップ（音高下降）", en: "Downstep", cat: "声調・イントネーション" },
  "ꜛ": { name: "アップステップ（音高上昇）", en: "Upstep", cat: "声調・イントネーション" },
  "↗": { name: "全体的上昇（グローバル・ライズ）", en: "Global rise", cat: "声調・イントネーション" },
  "↘": { name: "全体的下降（グローバル・フォール）", en: "Global fall", cat: "声調・イントネーション" },

  // 囲み・基本
  "[": { name: "角括弧（精密表記開始）", en: "Left square bracket (narrow transcription)", cat: "表記記号" },
  "]": { name: "角括弧（精密表記終了）", en: "Right square bracket (narrow transcription)", cat: "表記記号" },
  "/": { name: "スラッシュ（音素表記・簡略表記）", en: "Slash (broad phonemic transcription)", cat: "表記記号" },
  " ": { name: "空白（スペース）", en: "Space", cat: "基本" }
};
